alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias breload='clear; source ~/.bashrc'
alias clc='clear'
alias clean='make clean'
alias clear='FIRST_PROMPT=true;clear'
alias colours='for code in {0..255}; do num=`printf %03d $code`;echo -ne "\e[38;05;${num}m $num"; if [ $(($code % 16)) -eq 15 ]; then echo; fi; done'
alias diff='colordiff -u'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias mygrep='grep -rnI'
alias nemo='nemo `pwd`'
alias patch='patch -p0 -i'
alias sudo='sudo '
alias updateall='sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt autoremove'
alias watch='watch '
